config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comments_counter

  belongs_to :author, class_name: 'User'
  belongs_to :post

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.length)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = User.includes(:posts, :comments).find(params[:user_id]).posts.find(params[:post_id])
    @comments = @post.last_five_comments
  end

  def create
    parameters = comment_params
    puts parameters
    comment = Comment.new(post_id: params[:post_id], author_id: current_user.id, text: parameters[:text])
    comment.save

    if comment.save
      redirect_to user_post_path(id: params[:post_id])
    else
      redirect_to new_user_post_comment
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = User.includes(:posts, :comments).find(params[:user_id]).posts.find(params[:post_id])
    @comments = @post.last_five_comments
  end

  def create
    parameters = comment_params
    puts parameters
    comment = Comment.new(post_id: params[:post_id], author_id: current_user.id, text: parameters[:text])
    comment.save

    if comment.save
      redirect_to user_post_path(id: params[:post_id])
    else
      redirect_to new_user_post_comment
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/new.html.erb
<div id="newComment">
        <div id="postHeader">
                <h3 class="post-title">Post <%= @post.id %> by <%= @user.name %> </h3>
                <label class="counters">Comments:<%= @post.comments_counter %> Likes:<%= @post.likes_counter %> </label>
        </div>
        <p><%= @post.text %></p>
       <div id="formComment" >
            <%= form_with model: Comment.new, url: user_post_comments_path do |f| %>
            <%=f.hidden_field :post_id, :value => "#{@post.id}", readonly: true%>
            <%= f.label :text %><br>
            <%= f.text_field :text %><br>
            <%= f.submit "Add Comment" %>
            <% end %>
        </div>
</div>