config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter

  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def last_five_comments
    comments.order('created_at Desc').limit(5)
  end

  private

  def update_posts_counter
    author.update(postCounter: author.posts.length)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:comments, :author).find_by(author_id: params[:user_id], id: params[:id])
    @user = current_user
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    parameters = post_params
    post = Post.new(author_id: current_user.id, title: parameters[:title], text: parameters[:text])
    post.save
    if post.save
      redirect_to user_path(current_user)
    else
      redirect_to new_user_post_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Posts index</h1>
<p>Here is a list posts for users</p>
<div class="user-index bordered">
  <div>
    <img src="<%= @user.photo %>">
    <h1><%= @user.name %></h1>
  </div>
  <span>Number of posts:<%=@user.postCounter %></span>
</div>
<% @user.all_posts.each do  |post| %>
  <div class="post-mini bordered">
    <%= link_to user_post_path(@user, post) do %>
    <h3>Post #<%= post.id %> <%= post.title%> </h3>
    <% end %>
    <p><%= post.text %></p>
    <small>Comments:<%= post.comments_counter%>, Likes:<%= post.likes_counter%></small>
  </div>
    <div class="comments bordered">
      <% post.last_five_comments.each do |comment| %>
         <p><%=comment.author.name %>:<%= comment.text %></p>
      <% end %>
    </div>
<% end %>
<%= button_to "Paginations"%>

app/views/posts/new.html.erb
<div id="newPost">
<h1>New Post </h1>
<div class="user-index bordered">
  <div>
    <img src="<%= @user.photo %>">
    <h1><%= @user.name %></h1>
  </div>
  <span>Number of posts:<%=@user.postCounter %></span>
</div>
 <%= form_with model: @post, url: user_posts_path do |f| %>
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>
      <%= f.label :text %><br>
      <%= f.text_area :text %><br>
      <%= f.submit "Create Post" %>
    <% end %>
<div>

app/views/posts/show.html.erb
<h1>Posts show</h1>
<p>Here is a post for user</p>
<div class="post bordered">
  <div>
    <p>Post #<%= @post.id %> by <%=@post.author.name %><p>
    <small>Comments:<%= @post.comments_counter%>, Likes:<%= @post.likes_counter%></small>
  </div>
     <div>
      <h2><%= @post.title %></h2>
      <p><%= @post.text %><p>
     </div>
     </div>
     <div class="comments bordered">
     <h3>Comments: </h3>
       <% @post.comments.each do |comment| %>
          <p><%= comment.author.name%> : <%= comment.text %>
       <% end %>
     </div>
     <%= button_to "See all posts", user_posts_path(@user.id), method:'get'%>
      <%= button_to link_to "New Comment", new_user_post_comment_path(author_id: @user.id, post_id:@post.id) %>
     <%= button_to "Like", user_post_likes_path(@user, @post), 
     params: { like: { author_id: @user.id, post_id: @post.id}}%>